name: Build 3rd image

concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}-${{ inputs.nocobase_pr_number }}-${{ inputs.repository }}-${{ inputs.repo_pr_number }}
  cancel-in-progress: true

run-name: ${{ inputs.branch }}-${{ inputs.nocobase_pr_number }}-${{ inputs.repository }}-${{ inputs.repo_pr_number }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'base branch'
        required: true
      nocobase_pr_number:
        description: 'main repo pr number'
      repository:
        description: 'repo name'
      repo_pr_number:
        description: 'repo pr number'
      checkRunId:
        description: 'check run id'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
    steps:
      - name: Get info
        id: get-info
        shell: bash
        run: |
          echo "imageTag=$(echo 'pr-${{ inputs.repo_pr_number }}-${{ inputs.repository }}')" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.NOCOBASE_APP_ID }}
          private-key: ${{ secrets.NOCOBASE_APP_PRIVATE_KEY }}
          owner: nocobase
          repositories: nocobase,${{ inputs.repository }}
          skip-token-revoke: true
      - name: Update in_progress status
        if: ${{ inputs.checkRunId }}
        run: |
          gh api -X PATCH /repos/nocobase/${{ inputs.repository }}/check-runs/${{ inputs.checkRunId }} \
             -F 'status=in_progress' \
             -F 'details_url=https://github.com/2013xile/nocobase-ci/actions/runs/${{ github.run_id }}'
        env: 
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: nocobase/nocobase
          ref: ${{ inputs.branch }}
          token: ${{ steps.app-token.outputs.token }}
          submodules: true
      - name: Checkout nocobase/nocobase pr
        if: ${{ inputs.nocobase_pr_number != '' }}
        shell: bash
        run: |
          gh pr checkout ${{ inputs.nocobase_pr_number }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: nocobase/${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          path: packages/plugins/@${{ inputs.repository }}
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Checkout repository pr
        if: ${{ inputs.repo_pr_number != '' }}
        shell: bash
        run: |
          cd ./packages/plugins/@${{ inputs.repository }}/
          gh pr checkout ${{ inputs.repo_pr_number }}
          cd ../../../
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: rm .git
        run: |
          rm -rf packages/plugins/@${{ inputs.repository }}/.git
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name" && git add -A && git commit -m "tmp commit"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}
      - name: Set tags
        id: set-tags
        run: |
          echo "::set-output name=tags::${{ secrets.ALI_DOCKER_REGISTRY }}/nocobase/nocobase:${{ steps.get-info.outputs.imageTag }}"
      - name: Set variables
        run: |
          target_directory="./packages/plugins/@${{ inputs.repository }}"
          subdirectories=$(find "$target_directory" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | tr '\n' ' ')
          trimmed_variable=$(echo "$subdirectories" | xargs)
          packageNames="@${{ inputs.repository }}/${trimmed_variable// / @${{ inputs.repository }}/}"
          pluginNames="${trimmed_variable//plugin-/}"
          BEFORE_PACK_NOCOBASE="yarn add $packageNames -W --production"
          APPEND_PRESET_LOCAL_PLUGINS="${packageNames// /,}"
          echo "var1=$BEFORE_PACK_NOCOBASE" >> $GITHUB_OUTPUT
          echo "var2=$APPEND_PRESET_LOCAL_PLUGINS" >> $GITHUB_OUTPUT
        id: vars
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          build-args: |
            VERDACCIO_URL=http://localhost:4873/
            COMMIT_HASH=${GITHUB_SHA}
            PLUGINS_DIRS=pro-plugins
            BEFORE_PACK_NOCOBASE=${{ steps.vars.outputs.var1 }}
            APPEND_PRESET_LOCAL_PLUGINS=${{ steps.vars.outputs.var2 }}
          push: true
          tags: ${{ steps.set-tags.outputs.tags }}
      - name: Deploy NocoBase V2
        env:
          IMAGE_TAG: nocobase/nocobase:${{ steps.get-info.outputs.imageTag }}
        run: |
          echo $IMAGE_TAG
          export APP_NAME=$(echo $IMAGE_TAG | cut -d ":" -f 2)
          echo $APP_NAME
          curl --retry 2 --location --request POST "${{secrets.NOCOBASE_DEPLOY_HOST_V2}}$APP_NAME" \
            --header 'Content-Type: application/json' \
            -d "{
                \"tag\": \"$APP_NAME\",
                \"dialect\": \"postgres\"
            }"
      - name: Update success status
        if: ${{ inputs.checkRunId && always() }}
        run: |
          gh api -X PATCH /repos/nocobase/${{ inputs.repository }}/check-runs/${{ inputs.checkRunId }} \
             -F 'status=completed' \
             -F 'conclusion=${{ job.status }}' \
             -F 'details_url=https://github.com/2013xile/nocobase-ci/actions/runs/${{ github.run_id }}'
        env: 
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
